//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EMPId { get; set; }
        public string EmpName { get; set; }
        public Nullable<long> Salary { get; set; }
        public string Image { get; set; }
        public Nullable<long> Phone { get; set; }
    }
}
